# Generated by Django 3.0.6 on 2020-06-24 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_donante', models.CharField(max_length=30)),
                ('contacto_donante', models.CharField(max_length=40)),
                ('comedor_donacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comedores.Comedor')),
            ],
        ),
    ]
