# Generated by Django 3.0.6 on 2020-07-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='donacion_aceptada',
            field=models.BooleanField(default=False),
        ),
    ]
