# Generated by Django 3.0.6 on 2020-07-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0002_auto_20200630_2154'),
        ('donaciones', '0002_donacion_donacion_aceptada'),
    ]

    operations = [
        migrations.AddField(
            model_name='donacion',
            name='producto_donacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comedores.Producto'),
            preserve_default=False,
        ),
    ]
