# Generated by Django 3.0.6 on 2020-07-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedor',
            name='descripcion',
            field=models.TextField(null=True),
        ),
    ]
